import { useSession } from 'next-auth/client'
import type { NextPage } from 'next'
import Head from 'next/head'

import Home from '../src/pages/Home'
import LoginPage from './login'

const HomePage: NextPage = () => {
  const [session] = useSession()

  if (session) {
    return (
      <div>
        <Head>
          <title>Solid Lamp</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Home />
      </div>
    )
  }

  return (
    <LoginPage />
  )
}

export default HomePage
