import { useSession, signIn, signOut } from "next-auth/client"
import type { NextPage } from 'next'
import Head from 'next/head'

import Home from '../src/pages/Home'
import Login from '../src/pages/Login'

const HomePage: NextPage = () => {
  const { data: session } = useSession()

  if(session) {
    return (
      <div>
        <Head>
          <title>Solid Lamp</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Home />
      </div>
    )
  }
  return (
    <div>
      <Head>
        <title>Solid Lamp - Login</title>
        <meta name="description" content="Solid Lamp - Login" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
    </div>
  )
}

export default HomePage
